Update videosrt

diff --git a/videosrt b/videosrt
--- a/videosrt
+++ b/videosrt
@@ -1,61 +1,68 @@
 #!/bin/bash
 #translate subtile
 #https://subtitlestranslator.com/en/
-if [[ $2 == "" ]]; then
-echo "Videosrt"
-echo "--------"
-echo ""
-echo "cmd: videosrt info \"video.mkv\""
-echo "result: Stream #0:2(eng) Subtitle: subrip"
-echo ""
-echo "cmd: videosrt extract \"video.mkv\" \"0:2\""
-echo "result: Creation of video.mkv.srt"
-echo ""
-echo "cmd: videosrt convert \"video.mkv\""
-echo "result: Generate file with yellow subtile"
-exit
+if [ "$1" = "info" ]; then
+if ffmpeg -i "$2" 2>&1 | grep -q "No such file: $2"; then
+echo "No subtitles on the video"
+else
+subtitle_streams=$(ffmpeg -i "$2" -hide_banner -map 0:s -c copy -f null - 2>&1 | awk '/Stream.*Subtitle/ {print $0}')
+if [ -z "$subtitle_streams" ]; then
+echo "No subtitles on the video"
+else
+echo "Subtitles available:"
+echo "$subtitle_streams"
 fi
-if [[ $1 == "info" ]]; then
-if [ ! -f "$2" ]; then
-echo "No such file"
-exit
 fi
-script -c "ffmpeg -i \"$2\"" temposrt > temposrt
-grep -q "No such file or directory" temposrt; [ $? -eq 0 ] && echo "No subtitles on the video" || grep Subtitle temposrt
-rm temposrt
 exit
+
+elif [ "$1" = "extract" ]; then
+if [ -f "$2" ]; then
+if [ -f "${2}.srt" ]; then
+echo "Subtitle file already exists: $2.srt"
+else
+ffmpeg -i "$2" -map "$3" "${2}.srt" > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+echo "Subtitles extracted successfully: $2.srt"
+else
+echo "Failed to extract subtitles."
 fi
-if [[ $1 == "extract" ]]; then
-if [ ! -f "$2.srt" ]; then
-echo '#!/bin/bash' > temposrt.sh
-echo "ffmpeg -i \"$2\" -map \"$3\" \"$2.srt\"" >> temposrt.sh
-chmod +x temposrt.sh
-script -c "./temposrt.sh" temposrt > temposrt
-rm temposrt*
-if [ ! -f "$2.srt" ]; then
-echo "No subtitles extracted, check if subtitles are available with the command: videosrt info \"$2\""
-exit
 fi
-echo "Subtitle exported with name: $2.srt"
-exit
+else
+echo "No such file: $2"
 fi
-echo "$2.srt is already extracted"
-exit
+
+elif [ "$1" = "convert" ]; then
+if [ -e "$2.videosrt.mp4" ]; then
+echo "File already converted: $2.videosrt.mp4"
+elif [ ! -e "$2" ]; then
+echo "No such file: $2"
+elif [ ! -e "$3" ]; then
+echo "No such file: $3"
+else
+ffmpeg -i "$2" -filter:v "subtitles=filename='$3':force_style='Fontsize=34,PrimaryColour=&H0000ffff,BorderStyle=3'" -codec:v "libx264" -codec:a "mp3" "$2.videosrt.mp4"
 fi
-if [[ $1 == "convert" ]]; then
-if [ ! -f "$2.srt" ]; then
-echo "No subtitles found with the same file name, try renaming your file to \"$2.srt\" or check if subtitles are available with: videosrt info \"$2\""
+
+elif [ "$1" = "extract-yt" ]; then
+yt-dlp --list-subs "$2"
+echo "Language:"
+read language
+yt-dlp --write-subs "$language" --skip-download "$2"
+yt-dlp -f mp4 "$2"
 exit
-fi
-if [ ! -f "$2.conv.mp4" ]; then
-ffmpeg -i "$2" -filter:v "subtitles=filename=$2.srt:force_style='Fontsize=34,PrimaryColour=&H0000ffff,BorderStyle=3'" -codec:v "libx264" -codec:a "mp3" "$2.conv.mp4"
-if [ ! -f "$2.conv.mp4" ]; then
-echo "Error?"
-exit
-fi
-echo "$2.conv.mp4 converted"
-exit
-fi
-echo "$2.conv.mp4 is already converted"
-exit
+
+else
+echo ''
+echo 'videosrt info "video.mkv"'
+echo 'Displays information about the subtitles of the specified video'
+echo ''
+echo 'videosrt extract "video.mkv" "0:0"'
+echo 'Extracts subtitles from the specified video and saves them to an SRT file'
+echo ''
+echo 'videosrt convert "video.mkv" "video.mkv.srt"'
+echo 'Incorporates subtitles from an SRT file into a video in large, yellow and with a black background'
+echo ''
+echo 'videosrt extract-yt "link"'
+echo 'Displays the list of available subtitles for a YTvideo, choose language & extracts the subtitles into an SRT file and downloads the video in mp4'
+echo ''
+exit 1
 fi
